INSERT INTO Coins (symbol,name,sort,createdAt,updatedAt) VALUES ('BTC', 'Bitcoin',10,NOW(),NOW());
INSERT INTO Coins (symbol,name,sort,createdAt,updatedAt) VALUES ('ETH', 'Ethereum',9,NOW(),NOW());
INSERT INTO Coins (symbol,name,sort,createdAt,updatedAt) VALUES ('LTC', 'Litecoin',8,NOW(),NOW());
INSERT INTO Coins (symbol,name,sort,createdAt,updatedAt) VALUES ('XRP', 'XRP',0,NOW(),NOW());
INSERT INTO Coins (symbol,name,sort,createdAt,updatedAt) VALUES ('BCH', 'Bitcoin Cash',0,NOW(),NOW());
INSERT INTO Coins (symbol,name,sort,createdAt,updatedAt) VALUES ('BSV', 'Bitcoin SV',0,NOW(),NOW());
INSERT INTO Coins (symbol,name,sort,createdAt,updatedAt) VALUES ('EOS', 'EOS',0,NOW(),NOW());
INSERT INTO Coins (symbol,name,sort,createdAt,updatedAt) VALUES ('BNB', 'Binance Coin',0,NOW(),NOW());
INSERT INTO Coins (symbol,name,sort,createdAt,updatedAt) VALUES ('LINK', 'Chainlink',0,NOW(),NOW());
INSERT INTO Coins (symbol,name,sort,createdAt,updatedAt) VALUES ('ADA', 'Cardano',0,NOW(),NOW());
INSERT INTO Coins (symbol,name,sort,createdAt,updatedAt) VALUES ('XLM', 'Stellar',0,NOW(),NOW());
INSERT INTO Coins (symbol,name,sort,createdAt,updatedAt) VALUES ('XMR', 'Monero',0,NOW(),NOW());
INSERT INTO Coins (symbol,name,sort,createdAt,updatedAt) VALUES ('TRX', 'Tron',0,NOW(),NOW());
INSERT INTO Coins (symbol,name,sort,createdAt,updatedAt) VALUES ('ETC', 'Ethereum Classic',0,NOW(),NOW());
INSERT INTO Coins (symbol,name,sort,createdAt,updatedAt) VALUES ('DASH', 'Dash',0,NOW(),NOW());
INSERT INTO Coins (symbol,name,sort,createdAt,updatedAt) VALUES ('NEO', 'Neo',0,NOW(),NOW());
INSERT INTO Coins (symbol,name,sort,createdAt,updatedAt) VALUES ('ZEC', 'Zcash',0,NOW(),NOW());
INSERT INTO Coins (symbol,name,sort,createdAt,updatedAt) VALUES ('XEM', 'NEM',0,NOW(),NOW());
INSERT INTO Coins (symbol,name,sort,createdAt,updatedAt) VALUES ('ONT', 'Ontology',0,NOW(),NOW());
INSERT INTO Coins (symbol,name,sort,createdAt,updatedAt) VALUES ('VET', 'Vechain',0,NOW(),NOW());
INSERT INTO Coins (symbol,name,sort,createdAt,updatedAt) VALUES ('BAT', 'Basic Attention Token',0,NOW(),NOW());
INSERT INTO Coins (symbol,name,sort,createdAt,updatedAt) VALUES ('QTUM', 'Qtum',0,NOW(),NOW());
INSERT INTO Coins (symbol,name,sort,createdAt,updatedAt) VALUES ('ICX', 'ICON',0,NOW(),NOW());
INSERT INTO Coins (symbol,name,sort,createdAt,updatedAt) VALUES ('DCR', 'Decred',0,NOW(),NOW());
INSERT INTO Coins (symbol,name,sort,createdAt,updatedAt) VALUES ('ZRX', '0x',0,NOW(),NOW());
INSERT INTO Coins (symbol,name,sort,createdAt,updatedAt) VALUES ('LSK', 'Lisk',0,NOW(),NOW());
INSERT INTO Coins (symbol,name,sort,createdAt,updatedAt) VALUES ('RVN', 'Ravencoin',0,NOW(),NOW());
INSERT INTO Coins (symbol,name,sort,createdAt,updatedAt) VALUES ('BTG', 'Bitcoin Gold',0,NOW(),NOW());
INSERT INTO Coins (symbol,name,sort,createdAt,updatedAt) VALUES ('REP', 'Augur',0,NOW(),NOW());
INSERT INTO Coins (symbol,name,sort,createdAt,updatedAt) VALUES ('OMG', 'OmiseGO',0,NOW(),NOW());
INSERT INTO Coins (symbol,name,sort,createdAt,updatedAt) VALUES ('WAVES', 'WAVES',0,NOW(),NOW());
INSERT INTO Coins (symbol,name,sort,createdAt,updatedAt) VALUES ('NANO', 'Nano',0,NOW(),NOW());
INSERT INTO Coins (symbol,name,sort,createdAt,updatedAt) VALUES ('ENJ', 'Enjin Coin',0,NOW(),NOW());
INSERT INTO Coins (symbol,name,sort,createdAt,updatedAt) VALUES ('ZIL', 'Zilliqa',0,NOW(),NOW());
INSERT INTO Coins (symbol,name,sort,createdAt,updatedAt) VALUES ('ELF', 'aelf',0,NOW(),NOW());
INSERT INTO Coins (symbol,name,sort,createdAt,updatedAt) VALUES ('XZC', 'Zcoin',0,NOW(),NOW());
    